spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: moya4202344
  jpa:
    show-sql: true 
    hibernate:
      ddl-auto : update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      
     